version: "3.8"

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=webchat
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/.venv
      - /root/.cache
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/webchat
      - SECRET_KEY=your_secret_key_here
      - BACKEND_CORS_ORIGINS=["http://localhost:3000"]
      - PYTHONUNBUFFERED=1
      - POETRY_VIRTUALENVS_CREATE=false
    command: >
      sh -c "poetry run uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true # For file watching in Docker
      - WATCHPACK_POLLING=true # For webpack in Docker
    stdin_open: true
    tty: true

volumes:
  postgres_data:
